import { Activities, Observers, Permissions, Units } from './src/constants'

const NativeModules = require('react-native').NativeModules

export const HealthKit = {
  initHealthKit: NativeModules.AppleHealthKit.initHealthKit,
  isAvailable: NativeModules.AppleHealthKit.isAvailable,
  getBiologicalSex: NativeModules.AppleHealthKit.getBiologicalSex,
  getBloodType: NativeModules.AppleHealthKit.getBloodType,
  getDateOfBirth: NativeModules.AppleHealthKit.getDateOfBirth,
  getLatestWeight: NativeModules.AppleHealthKit.getLatestWeight,
  getWeightSamples: NativeModules.AppleHealthKit.getWeightSamples,
  saveWeight: NativeModules.AppleHealthKit.saveWeight,
  getLatestHeight: NativeModules.AppleHealthKit.getLatestHeight,
  getHeightSamples: NativeModules.AppleHealthKit.getHeightSamples,
  saveHeight: NativeModules.AppleHealthKit.saveHeight,
  getLatestWaistCircumference: NativeModules.AppleHealthKit.getLatestWaistCircumference,
  getWaistCircumferenceSamples: NativeModules.AppleHealthKit.getWaistCircumferenceSamples,
  saveWaistCircumference: NativeModules.AppleHealthKit.saveWaistCircumference,
  getLatestPeakFlow: NativeModules.AppleHealthKit.getLatestPeakFlow,
  getPeakFlowSamples: NativeModules.AppleHealthKit.getPeakFlowSamples,
  savePeakFlow: NativeModules.AppleHealthKit.savePeakFlow,
  saveLeanBodyMass: NativeModules.AppleHealthKit.saveLeanBodyMass,
  getLatestBmi: NativeModules.AppleHealthKit.getLatestBmi,
  getBmiSamples: NativeModules.AppleHealthKit.getBmiSamples,
  saveBmi: NativeModules.AppleHealthKit.saveBmi,
  getLatestBodyFatPercentage: NativeModules.AppleHealthKit.getLatestBodyFatPercentage,
  getBodyFatPercentageSamples: NativeModules.AppleHealthKit.getBodyFatPercentageSamples,
  getLatestLeanBodyMass: NativeModules.AppleHealthKit.getLatestLeanBodyMass,
  getLeanBodyMassSamples: NativeModules.AppleHealthKit.getLeanBodyMassSamples,
  getStepCount: NativeModules.AppleHealthKit.getStepCount,
  getSamples: NativeModules.AppleHealthKit.getSamples,
  getAnchoredWorkouts: NativeModules.AppleHealthKit.getAnchoredWorkouts,
  getDailyStepCountSamples: NativeModules.AppleHealthKit.getDailyStepCountSamples,
  saveSteps: NativeModules.AppleHealthKit.saveSteps,
  saveWalkingRunningDistance: NativeModules.AppleHealthKit.saveWalkingRunningDistance,
  getDistanceWalkingRunning: NativeModules.AppleHealthKit.getDistanceWalkingRunning,
  getDailyDistanceWalkingRunningSamples: NativeModules.AppleHealthKit.getDailyDistanceWalkingRunningSamples,
  getDistanceCycling: NativeModules.AppleHealthKit.getDistanceCycling,
  getDailyDistanceCyclingSamples: NativeModules.AppleHealthKit.getDailyDistanceCyclingSamples,
  getFlightsClimbed: NativeModules.AppleHealthKit.getFlightsClimbed,
  getDailyFlightsClimbedSamples: NativeModules.AppleHealthKit.getDailyFlightsClimbedSamples,
  getEnergyConsumedSamples: NativeModules.AppleHealthKit.getEnergyConsumedSamples,
  getProteinSamples: NativeModules.AppleHealthKit.getProteinSamples,
  getFiberSamples: NativeModules.AppleHealthKit.getFiberSamples,
  getTotalFatSamples: NativeModules.AppleHealthKit.getTotalFatSamples,
  saveFood: NativeModules.AppleHealthKit.saveFood,
  saveWater: NativeModules.AppleHealthKit.saveWater,
  getWater: NativeModules.AppleHealthKit.getWater,
  saveHeartRateSample: NativeModules.AppleHealthKit.saveHeartRateSample,
  getWaterSamples: NativeModules.AppleHealthKit.getWaterSamples,
  getHeartRateSamples: NativeModules.AppleHealthKit.getHeartRateSamples,
  getRestingHeartRate: NativeModules.AppleHealthKit.getRestingHeartRate,
  getWalkingHeartRateAverage: NativeModules.AppleHealthKit.getWalkingHeartRateAverage,
  getActiveEnergyBurned: NativeModules.AppleHealthKit.getActiveEnergyBurned,
  getBasalEnergyBurned: NativeModules.AppleHealthKit.getBasalEnergyBurned,
  getAppleExerciseTime: NativeModules.AppleHealthKit.getAppleExerciseTime,
  getAppleStandTime: NativeModules.AppleHealthKit.getAppleStandTime,
  getVo2MaxSamples: NativeModules.AppleHealthKit.getVo2MaxSamples,
  getBodyTemperatureSamples: NativeModules.AppleHealthKit.getBodyTemperatureSamples,
  getBloodPressureSamples: NativeModules.AppleHealthKit.getBloodPressureSamples,
  getRespiratoryRateSamples: NativeModules.AppleHealthKit.getRespiratoryRateSamples,
  getHeartRateVariabilitySamples: NativeModules.AppleHealthKit.getHeartRateVariabilitySamples,
  getHeartbeatSeriesSamples: NativeModules.AppleHealthKit.getHeartbeatSeriesSamples,
  getRestingHeartRateSamples: NativeModules.AppleHealthKit.getRestingHeartRateSamples,
  getBloodGlucoseSamples: NativeModules.AppleHealthKit.getBloodGlucoseSamples,
  getCarbohydratesSamples: NativeModules.AppleHealthKit.getCarbohydratesSamples,
  saveBloodGlucoseSample: NativeModules.AppleHealthKit.saveBloodGlucoseSample,
  saveCarbohydratesSample: NativeModules.AppleHealthKit.saveCarbohydratesSample,
  deleteBloodGlucoseSample: NativeModules.AppleHealthKit.deleteBloodGlucoseSample,
  deleteCarbohydratesSample: NativeModules.AppleHealthKit.deleteCarbohydratesSample,
  getSleepSamples: NativeModules.AppleHealthKit.getSleepSamples,
  getInfo: NativeModules.AppleHealthKit.getInfo,
  getMindfulSession: NativeModules.AppleHealthKit.getMindfulSession,
  saveMindfulSession: NativeModules.AppleHealthKit.saveMindfulSession,
  getWorkoutRouteSamples: NativeModules.AppleHealthKit.getWorkoutRouteSamples,
  saveWorkout: NativeModules.AppleHealthKit.saveWorkout,
  getAuthStatus: NativeModules.AppleHealthKit.getAuthStatus,
  getLatestBloodAlcoholContent: NativeModules.AppleHealthKit.getLatestBloodAlcoholContent,
  getBloodAlcoholContentSamples: NativeModules.AppleHealthKit.getBloodAlcoholContentSamples,
  saveBloodAlcoholContent: NativeModules.AppleHealthKit.saveBloodAlcoholContent,
  getDistanceSwimming: NativeModules.AppleHealthKit.getDistanceSwimming,
  getDailyDistanceSwimmingSamples: NativeModules.AppleHealthKit.getDailyDistanceSwimmingSamples,
  getOxygenSaturationSamples: NativeModules.AppleHealthKit.getOxygenSaturationSamples,
  getElectrocardiogramSamples: NativeModules.AppleHealthKit.getElectrocardiogramSamples,
  saveBodyFatPercentage: NativeModules.AppleHealthKit.saveBodyFatPercentage,
  saveBodyTemperature: NativeModules.AppleHealthKit.saveBodyTemperature,
  getEnvironmentalAudioExposure: NativeModules.AppleHealthKit.getEnvironmentalAudioExposure,
  getHeadphoneAudioExposure: NativeModules.AppleHealthKit.getHeadphoneAudioExposure,
  getClinicalRecords: NativeModules.AppleHealthKit.getClinicalRecords,
  getActivitySummary: NativeModules.AppleHealthKit.getActivitySummary,
  getInsulinDeliverySamples: NativeModules.AppleHealthKit.getInsulinDeliverySamples,
  saveInsulinDeliverySample: NativeModules.AppleHealthKit.saveInsulinDeliverySample,
  deleteInsulinDeliverySample: NativeModules.AppleHealthKit.deleteInsulinDeliverySample,

  Constants: {
    Activities,
    Observers,
    Permissions,
    Units,
  },
}

module.exports = HealthKit
